"""Layouts for FM26 build 26.3.2+2329565, the final FM26 update."""

from __future__ import annotations

import struct

from fmsave._layouts import (
    FULL_SAVE_MINIMUM_GAME_DB_BYTES,
    ClubRecordLayout,
    ClubStatusLayout,
    GameInfoLayout,
    LayoutEntry,
    NamePoolLayout,
    PersonBlockLayout,
    PlayerRecordLayout,
    SaveSummaryLayout,
    TeamListLayout,
)

BUILD = "26.3.2+2329565"

GAME_INFO = GameInfoLayout(
    db_version_length_offset=8,
    max_db_version_bytes=64,
    build_number_offsets_after_db_version=(34, 38, 202),
    game_date_offset_after_db_version=172,
)

SAVE_SUMMARY = SaveSummaryLayout(
    version_pattern=r"([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,4})\+([0-9]{1,10})",
    max_version_bytes=32,
)

NAME_POOLS = NamePoolLayout(
    signature=struct.pack("<6I", 46421, 0, 1024, 256, 2048, 0),
    max_name_bytes=64,
    minimum_entries_per_pool=50_000,
    minimum_applies_from_bytes=FULL_SAVE_MINIMUM_GAME_DB_BYTES,
)

CLUB_RECORDS = ClubRecordLayout(
    anchor=b"\xff\xff\xff\xff",
    anchor_offset=17,
    club_index_offset=0,
    uid_offset=4,
    uid_copy_offset=8,
    zero_byte_offset=12,
    nation_offset=13,
    fa_nation_offset=21,
    nation_copy_offset=25,
    city_offset=29,
    long_name_offset=39,
    nation_id_range=(1, 999),
    max_name_bytes=64,
    stop_gap_bytes=64 * 1024,
)

# A null date is day 1 of 1900; the float anchor is 1.0.
TEAM_LISTS = TeamListLayout(
    null_date_triple=struct.pack("<HH", 1, 1900) * 3,
    float_anchor=struct.pack("<f", 1.0),
    float_anchor_offset=33,
    minimum_float_anchor_record_offset=40,
    counts_offset=37,
    first_entry_bytes=25,
    first_entry_lead_byte=0x02,
    second_entry_bytes=12,
    second_entry_lead_byte=0x01,
    filler_bytes=9,
    team_count_range=(1, 8),
    team_id_range=(1, 3_000_000),
)

CLUB_STATUSES = ClubStatusLayout(
    ordinal_offset=-4,
    ordinal_limit=200_000,
    kind_offset=8,
    normal_kind=0x0A,
    stub_kind=0x0B,
    position_offset=10,
    reputation_offset=11,
    reputation_range=(1, 10_000),
    # A power of two at least four times the largest gap between consecutive accepted status
    # records measured on real saves.
    search_window_bytes=256 * 1024,
    maximum_leading_misses=16,
)

PLAYER_RECORDS = PlayerRecordLayout(
    marker=bytes.fromhex("01006c07"),
    marker_offset=102,
    pindex_offset=-19,
    uid_offset=-15,
    uid_copy_offset=-11,
    home_reputation_offset=-6,
    current_reputation_offset=-4,
    world_reputation_offset=-2,
    current_ability_offset=0,
    current_ability_range=(1, 200),
    potential_ability_offset=2,
    potential_ability_range=(-10, 200),
    reputation_bucket_offset=8,
    reputation_bucket_range=(0, 200),
    team_id_offset=16,
    ratings_offset=24,
    ratings_count=15,
    rating_range=(1, 20),
    attributes_offset=39,
    attribute_count=54,
    attribute_range=(1, 100),
    left_foot_index=24,
    right_foot_index=25,
    transfer_value_offset=93,
    transfer_value_placeholder=300_000_000,
    club_join_date_offset=98,
    match_sharpness_offset=106,
    condition_offset=110,
    height_offset=121,
    decode_extent=122,
    position_codes=(
        "GK",
        "SW",
        "DL",
        "DC",
        "DR",
        "DM",
        "ML",
        "MC",
        "MR",
        "AML",
        "AMC",
        "AMR",
        "STC",
        "WBL",
        "WBR",
    ),
    attribute_field_order=(
        "crossing",
        "dribbling",
        "finishing",
        "heading",
        "long_shots",
        "marking",
        "off_the_ball",
        "passing",
        "penalty_taking",
        "tackling",
        "vision",
        "one_on_ones",
        "aerial_reach",
        "command_of_area",
        "communication",
        "kicking",
        "throwing",
        "anticipation",
        "decisions",
        "handling",
        "positioning",
        "reflexes",
        "first_touch",
        "technique",
        "flair",
        "corners",
        "teamwork",
        "work_rate",
        "long_throws",
        "eccentricity",
        "rushing_out",
        "punching",
        "acceleration",
        "free_kick_taking",
        "strength",
        "stamina",
        "pace",
        "jumping_reach",
        "leadership",
        "dirtiness",
        "balance",
        "bravery",
        "consistency",
        "aggression",
        "agility",
        "important_matches",
        "injury_proneness",
        "versatility",
        "natural_fitness",
        "determination",
        "composure",
        "concentration",
    ),
)

PERSON_BLOCKS = PersonBlockLayout(
    window_start_offset=100,
    personality_offset_from_birth=21,
    personality_count=8,
    personality_range=(1, 20),
    date_zero_bytes_offset_from_birth=14,
    date_zero_bytes_count=7,
    legal_name_length_min=2,
    legal_name_length_max=80,
    name_id_limit=2**23,
    first_name_id_offset_from_block_start=0,
    surname_id_offset_from_block_start=5,
    common_name_id_offset_from_block_start=10,
    legal_name_length_offset_from_block_start=15,
    legal_name_offset_from_block_start=19,
    trait_bits_offset_from_block_start=-8,
    nation_id_offset_from_birth=13,
    relation_present_offset_from_birth=37,
    relation_count_offset_from_birth=38,
    relation_entries_offset_from_birth=39,
    relation_entry_bytes=16,
    second_nation_pair=(8, 9),
    home_grown_nation_pair=(8, 70),
    home_grown_club_pair=(1, 72),
)

LAYOUTS: tuple[LayoutEntry, ...] = (
    LayoutEntry(region="game_info", schema=46, build=BUILD, layout=GAME_INFO),
    LayoutEntry(region="save_game_summary", schema=29, build=BUILD, layout=SAVE_SUMMARY),
    LayoutEntry(region="game_db", schema=4000, build=BUILD, layout=NAME_POOLS),
    LayoutEntry(region="game_db", schema=4000, build=BUILD, layout=CLUB_RECORDS),
    LayoutEntry(region="game_db", schema=4000, build=BUILD, layout=TEAM_LISTS),
    LayoutEntry(region="game_db", schema=4000, build=BUILD, layout=CLUB_STATUSES),
    LayoutEntry(region="game_db", schema=4000, build=BUILD, layout=PLAYER_RECORDS),
    LayoutEntry(region="game_db", schema=4000, build=BUILD, layout=PERSON_BLOCKS),
)
