"""Layouts for FM26 build 26.3.2+2329565, the final FM26 update."""

from __future__ import annotations

import struct

from fmsave._layouts import (
    FULL_SAVE_MINIMUM_GAME_DB_BYTES,
    ClubRecordLayout,
    ClubStatusLayout,
    ContractLayout,
    GameInfoLayout,
    GateBounds,
    HumansLayout,
    LayoutEntry,
    NamePoolLayout,
    PersonBlockLayout,
    PlayerRecordLayout,
    SaveSummaryLayout,
    SummaryStringsLayout,
    SuspensionLayout,
    TeamListLayout,
)

BUILD = "26.3.2+2329565"

GAME_INFO = GameInfoLayout(
    db_version_length_offset=8,
    max_db_version_bytes=64,
    build_number_offsets_after_db_version=(34, 38, 202),
    game_date_offset_after_db_version=172,
)

SAVE_SUMMARY = SaveSummaryLayout(
    version_pattern=r"([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,4})\+([0-9]{1,10})",
    max_version_bytes=32,
)

# Strings start right after the 8-byte section header; control characters end a candidate.
SUMMARY_STRINGS = SummaryStringsLayout(
    strings_start_offset=8,
    string_length_range=(2, 120),
    lowest_code_point=0x20,
)

HUMANS = HumansLayout(
    human_count_offset=8,
    first_selector_offset=10,
    person_uid_offset=4,
    person_uid_copy_offset=8,
)

NAME_POOLS = NamePoolLayout(
    signature=struct.pack("<6I", 46421, 0, 1024, 256, 2048, 0),
    max_name_bytes=64,
    minimum_entries_per_pool=50_000,
    minimum_applies_from_bytes=FULL_SAVE_MINIMUM_GAME_DB_BYTES,
)

CLUB_RECORDS = ClubRecordLayout(
    anchor=b"\xff\xff\xff\xff",
    anchor_offset=17,
    club_index_offset=0,
    uid_offset=4,
    uid_copy_offset=8,
    zero_byte_offset=12,
    nation_offset=13,
    fa_nation_offset=21,
    nation_copy_offset=25,
    city_offset=29,
    long_name_offset=39,
    nation_id_range=(1, 999),
    max_name_bytes=64,
    stop_gap_bytes=64 * 1024,
)

# A null date is day 1 of 1900; the float anchor is 1.0.
TEAM_LISTS = TeamListLayout(
    null_date_triple=struct.pack("<HH", 1, 1900) * 3,
    float_anchor=struct.pack("<f", 1.0),
    float_anchor_offset=33,
    minimum_float_anchor_record_offset=40,
    counts_offset=37,
    first_entry_bytes=25,
    first_entry_lead_byte=0x02,
    second_entry_bytes=12,
    second_entry_lead_byte=0x01,
    filler_bytes=9,
    team_count_range=(1, 8),
    team_id_range=(1, 3_000_000),
    # At most 3 affiliated teams have been seen on one club; the cap leaves room for more.
    affiliate_count_range=(0, 8),
)

CLUB_STATUSES = ClubStatusLayout(
    ordinal_offset=-4,
    ordinal_limit=200_000,
    kind_offset=8,
    normal_kind=0x0A,
    stub_kind=0x0B,
    position_offset=10,
    reputation_offset=11,
    reputation_range=(1, 10_000),
    # A power of two at least four times the largest gap between consecutive accepted status
    # records measured on real saves.
    search_window_bytes=256 * 1024,
    confirmation_offset=-18,
    confirmation_zero_bytes=10,
    maximum_leading_misses=16,
)

PLAYER_RECORDS = PlayerRecordLayout(
    marker=bytes.fromhex("01006c07"),
    marker_offset=102,
    pindex_offset=-19,
    uid_offset=-15,
    uid_copy_offset=-11,
    home_reputation_offset=-6,
    current_reputation_offset=-4,
    world_reputation_offset=-2,
    current_ability_offset=0,
    current_ability_range=(1, 200),
    potential_ability_offset=2,
    potential_ability_range=(-10, 200),
    reputation_bucket_offset=8,
    reputation_bucket_range=(0, 200),
    team_id_offset=16,
    ratings_offset=24,
    ratings_count=15,
    rating_range=(1, 20),
    attributes_offset=39,
    attribute_count=54,
    attribute_range=(1, 100),
    left_foot_index=24,
    right_foot_index=25,
    transfer_value_offset=93,
    transfer_value_placeholder=300_000_000,
    club_join_date_offset=98,
    match_sharpness_offset=106,
    condition_offset=110,
    height_offset=121,
    decode_extent=122,
    position_codes=(
        "GK",
        "SW",
        "DL",
        "DC",
        "DR",
        "DM",
        "ML",
        "MC",
        "MR",
        "AML",
        "AMC",
        "AMR",
        "STC",
        "WBL",
        "WBR",
    ),
    attribute_field_order=(
        "crossing",
        "dribbling",
        "finishing",
        "heading",
        "long_shots",
        "marking",
        "off_the_ball",
        "passing",
        "penalty_taking",
        "tackling",
        "vision",
        "handling",
        "aerial_reach",
        "command_of_area",
        "communication",
        "kicking",
        "throwing",
        "anticipation",
        "decisions",
        "one_on_ones",
        "positioning",
        "reflexes",
        "first_touch",
        "technique",
        "flair",
        "corners",
        "teamwork",
        "work_rate",
        "long_throws",
        "eccentricity",
        "rushing_out",
        "punching",
        "acceleration",
        "free_kick_taking",
        "strength",
        "stamina",
        "pace",
        "jumping_reach",
        "leadership",
        "dirtiness",
        "balance",
        "bravery",
        "consistency",
        "aggression",
        "agility",
        "important_matches",
        "injury_proneness",
        "versatility",
        "natural_fitness",
        "determination",
        "composure",
        "concentration",
    ),
)

PERSON_BLOCKS = PersonBlockLayout(
    window_start_offset=100,
    personality_offset_from_birth=21,
    personality_count=8,
    personality_range=(1, 20),
    date_zero_bytes_offset_from_birth=14,
    date_zero_bytes_count=7,
    legal_name_length_min=2,
    legal_name_length_max=80,
    name_id_limit=2**23,
    first_name_id_offset_from_block_start=0,
    surname_id_offset_from_block_start=5,
    common_name_id_offset_from_block_start=10,
    legal_name_length_offset_from_block_start=15,
    legal_name_offset_from_block_start=19,
    trait_bits_offset_from_block_start=-8,
    nation_id_offset_from_birth=13,
    relation_present_offset_from_birth=37,
    relation_count_offset_from_birth=38,
    relation_entries_offset_from_birth=39,
    relation_entry_bytes=16,
    second_nation_pair=(8, 9),
    home_grown_nation_pair=(8, 70),
    home_grown_club_pair=(1, 72),
    relation_referenced_offset_in_entry=0,
    relation_kind_role_offset_in_entry=10,
    relation_qualifier_offset_in_entry=12,
    relation_sentinel_offset_in_entry=15,
    # 100 when the player holds the second nationality, 15 when the player is eligible for it.
    second_nation_qualifiers=(15, 100),
    relation_sentinel_value=0xFF,
)

CONTRACTS = ContractLayout(
    tag=bytes.fromhex("01006c07"),
    chain_window_start_offset=-30,
    chain_window_end_offset=-30,
    selector_offset=5,
    start_offset=-19,
    team_id_offset=9,
    wage_offset=17,
    tail_base_offset=66,
    tail_step_bytes=29,
    tail_max_event_count=200,
    tail_sentinel_byte_offset=3,
    tail_sentinel_byte_value=3,
    tail_sentinel_word_offset=4,
    tail_sentinel_word_value=4,
    tail_e2_offset=2,
    tail_e8_offset=8,
    tail_e12_offset=12,
    tail_e16_offset=16,
    tail_e20_offset=20,
    tail_e24_offset=24,
    tail_end_offset=28,
    tail_squad_status_offset=36,
    tail_e37_offset=37,
    tail_e38_offset=38,
    tail_e39_offset=39,
    tail_event_count_offset=42,
    # The loan blocks seen sit at most a few steps back; the cap leaves room for far more.
    loan_block_max_event_count=60,
    clause_step_bytes=8,
    clause_max_count=23,
    clause_ff_offset=-16,
    clause_ff_count=8,
    clause_zero_offset=-8,
    clause_zero_count=3,
    clause_count_offset=-5,
    clause_entries_offset=-4,
    clause_entry_bytes=8,
    clause_value_offset=0,
    clause_parameter_offset=4,
    clause_kind_offset=6,
    clause_team_marker_id_bytes=4,
    clause_competition_count_bytes=1,
    clause_competition_item_bytes=31,
    clause_competition_item_prefix=bytes.fromhex("010001006c07"),
    # At most 3 competition items and 3 award items have been seen on one contract; both caps
    # leave room for far longer lists.
    clause_competition_max_count=32,
    clause_award_flag_bytes=1,
    clause_award_count_bytes=4,
    clause_award_item_bytes=15,
    clause_award_item_prefix=bytes.fromhex("0100"),
    clause_award_max_count=32,
    clause_trailer_bytes=2,
    head_gate_offset=-35,
    head_gate_value=5,
    head_type_offset=-33,
    head_money_a_offset=-32,
    head_money_b_offset=-28,
    head_money_c_offset=-24,
    fallback_start_from_record=110,
    fallback_end_margin=90,
    fallback_nonzero_offset=8,
    fallback_nonzero_length=8,
    fallback_end_date_offset=0,
    fallback_start_date_offset=4,
    fallback_gate_length=16,
)

# A suspension entry is 20 bytes long; its signature bytes pin 5 of them.
SUSPENSIONS = SuspensionLayout(
    signature=((4, 0xFF), (5, 0xFF), (13, 0x05), (15, 0xFF), (18, 0xFF)),
    unknown_e7_offset=7,
    issued_date_offset=9,
    unknown_e14_offset=14,
    competition_id_offset=16,
    owner_back_offset=30,
    competition_id_exclusive_range=(0, 60_000),
)

# Bounds that depend on career stage (join dates, contract chains, bans) are kept wide, since a
# failed check on the player pass stops players, contracts and suspensions together.
GATE_BOUNDS = GateBounds(
    minimum_applies_from_bytes=FULL_SAVE_MINIMUM_GAME_DB_BYTES,
    height_range_cm=(150, 210),
    age_range_years=(14, 45),
    home_reputation_window=1_000,
    condition_sharpness_maximum=10_000,
    natural_goalkeeper_rating=18,
    goalkeeper_block_low_maximum=30,
    players_minimum=(5_000, None),
    person_blocks=(0.99, None),
    names_resolved=(0.995, None),
    relation_sentinel=(0.999, None),
    second_nation_qualifier=(0.995, None),
    # Reading the attribute bytes one position late moves this share below the bound, and one
    # position early moves it above, so the bound stays narrow.
    handling_above_finishing=(0.20, 0.30),
    # Handling and throwing are the first and last of six adjacent goalkeeping attributes, which
    # outfield players rate low. Reading the attribute bytes one position early or late puts an
    # outfield attribute in one of the two, so this share falls far below the bound.
    outfield_goalkeeper_block_low=(0.90, None),
    with_natural_position=(0.97, None),
    height_in_range=(0.999, None),
    height_median=(170, 190),
    age_median=(20, 30),
    aged_in_range=(0.995, None),
    condition_sharpness_in_range=(0.999, None),
    join_date_valid=(0.05, 0.95),
    world_not_above_current=(0.95, None),
    home_near_current=(0.95, None),
    team_resolved=(0.98, None),
    home_grown_club_refs_resolved=(0.98, None),
    players_with_chain=(0.70, None),
    no_contract_in_effect=(None, 0.05),
    date_marked_chain_records=(None, 0.05),
    tails_parsed=(0.70, None),
    tails_without_clause_table=(None, 0.001),
    clause_terminator=(0.999, None),
    contract_head=(0.65, None),
    past_dated_tail_ends=(None, 0.05),
    chain_teams_resolved=(0.98, None),
    clubs_minimum=(5_000, None),
    team_lists_found=(0.999, None),
    status_normal=(0.98, None),
    status_confirmation=(0.95, None),
    affiliate_lists_found=(0.005, None),
    affiliate_teams_linked=(0.99, None),
    suspension_share_of_players=(None, 0.10),
    issued_after_clock=(None, 0.01),
)

LAYOUTS: tuple[LayoutEntry, ...] = (
    LayoutEntry(region="game_info", schema=46, build=BUILD, layout=GAME_INFO),
    LayoutEntry(region="save_game_summary", schema=29, build=BUILD, layout=SAVE_SUMMARY),
    LayoutEntry(region="save_game_summary", schema=29, build=BUILD, layout=SUMMARY_STRINGS),
    LayoutEntry(region="game_db", schema=4000, build=BUILD, layout=NAME_POOLS),
    LayoutEntry(region="game_db", schema=4000, build=BUILD, layout=CLUB_RECORDS),
    LayoutEntry(region="game_db", schema=4000, build=BUILD, layout=TEAM_LISTS),
    LayoutEntry(region="game_db", schema=4000, build=BUILD, layout=CLUB_STATUSES),
    LayoutEntry(region="game_db", schema=4000, build=BUILD, layout=PLAYER_RECORDS),
    LayoutEntry(region="game_db", schema=4000, build=BUILD, layout=PERSON_BLOCKS),
    LayoutEntry(region="game_db", schema=4000, build=BUILD, layout=CONTRACTS),
    LayoutEntry(region="game_db", schema=4000, build=BUILD, layout=SUSPENSIONS),
    LayoutEntry(region="humans", schema=21, build=BUILD, layout=HUMANS),
    LayoutEntry(region="game_db", schema=4000, build=BUILD, layout=GATE_BOUNDS),
)
